# GENERATE TIME: Sun May 18 10:20:28 2025
# CMD:
# train.py -opt options/train_span_ft3.toml --auto_resume


name = "train_span_ll63_per20_gane30_con_ldl_b20_lr50+8"
model_type = "image"
scale = 2
#use_amp = true
#bfloat16 = true
#fast_matmul = true
#compile = true
#manual_seed = 1024

[datasets.train]
type = "paired"
dataroot_gt = '/mnt/dataset/nomosv2_all_low_ll63_LR_2x_gt'
dataroot_lq = '/mnt/dataset/nomosv2_all_low_ll63_LR_2x_degraded'
patch_size = 64
batch_size = 20
#accumulate = 1
#augmentation = [ "none", "mixup", "cutmix", "resizemix" ] # [ "cutblur" ]
#aug_prob = [ 0.5, 0.1, 0.1, 0.1 ] # [ 0.7 ]

[datasets.val]
name = "val"
type = "paired"
dataroot_gt = '/mnt/dataset/DIV2K_valid_low_ll63_LR_2x_gt'
dataroot_lq = '/mnt/dataset/DIV2K_valid_low_ll63_LR_2x_degraded'

[datasets.val_single]
name = "val_single"
type = "single"
dataroot_lq = '/mnt/dataset/problem_lr'

[val]
val_freq = 2500
#tile = 200
[val.metrics.psnr]
type = "calculate_psnr"
[val.metrics.ssim]
type = "calculate_ssim"
#[val.metrics.dists]
#type = "calculate_dists"
#better = "lower"

[path]
pretrain_network_g = 'experiments/train_span_pt_ll63/models/net_g_100000.pth'
#pretrain_network_d = 'experiments/train_span_ll66_per20_gane30_con_ldl_b20/models/net_d_200000.pth'

[network_g]
type = "span"

[network_d]
type = "ea2fpn"

[train]
ema = 0.999
#sam = "fsam"
#sam_init = 1000
#eco = true
#eco_init = 15000
#wavelet_guided = true
#wavelet_init = 80000
match_lq_colors = true

[train.optim_g]
type = "adan_sf"
lr = 5e-4
betas = [ 0.98, 0.92, 0.99 ]
weight_decay = 0.01
schedule_free = true
warmup_steps = 2500

[train.optim_d]
type = "adan_sf"
lr = 8e-5
betas = [ 0.98, 0.92, 0.99 ]
weight_decay = 0.01
schedule_free = true
warmup_steps = 2500

#  losses

[train.pixel_opt]
type = "L1Loss"
loss_weight = 10.0

[train.mssim_opt]
type = "mssim_loss"
loss_weight = 3.0

[train.consistency_opt]
type = "consistency_loss"
loss_weight = 1.0
criterion = "chc"
#saturation = 1.0
#brightness = 1.0

[train.perceptual_opt]
type = "vgg_perceptual_loss"
loss_weight = 0.2
criterion = "chc"
#patchloss = true
#ipk = true
#patch_weight = 1.0

[train.gan_opt]
type = "gan_loss"
gan_type = "bce"
loss_weight = 0.003

#[train.dists_opt]
#type = "dists_loss"
#loss_weight = 0.5

[train.ldl_opt]
type = "ldl_loss"
loss_weight = 1.0
criterion = "chc"

#[train.ff_opt]
#type = "ff_loss"
#loss_weight = 1.0

#[train.gw_opt]
#type = "gw_loss"
#loss_weight = 1.0

[logger]
total_iter = 500000
save_checkpoint_freq = 2500
use_tb_logger = true
#save_tb_img = true
#print_freq = 100
